---
title: "`r params$region` `r params$species` geostatistical index standardization"
author: ""
date: "`r Sys.Date()`"
output: bookdown::html_document2
params:
    species: "Pacific Cod"
    region: "SYN QCS"
    covariate_type: "with depth" # or "no depth"
    update_model: TRUE # will over write past models; will always attempt if none exists
    update_index: TRUE
    share_range: TRUE
    anisotropy: FALSE
    qq_residuals: FALSE
    silent: TRUE
    cutoff: 10
    cutoff_wchg: 7
    starr_mode: TRUE
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(
  fig.width = 11,
  fig.asp = 0.618,
  out.width = "80%",
  echo = FALSE, 
  warning = FALSE, 
  message = FALSE,
  comment = "#>",
  collapse = TRUE,
  fig.align = "center"
)

library(dplyr)
library(ggplot2)
library(sdmTMB)
library(here)

# options(scipen = 999)
theme_set(
  theme_bw(base_size = 14)
)

dir.create(here("predictions"), showWarnings = FALSE)
dir.create(here("indices"), showWarnings = FALSE)
dir.create(here("figs"), showWarnings = FALSE)
```

```{r assertions}
stopifnot(params$covariate_type %in% c("with depth", "no depth"))
stopifnot(params$region %in% c("SYN WCHG", "SYN QCS", "SYN HS", "SYN WCVI"))
stopifnot(is.character(params$species))
stopifnot(is.numeric(params$cutoff))
stopifnot(is.numeric(params$cutoff_wchg))
stopifnot(params$cutoff > 0)
stopifnot(params$cutoff_wchg > 0)
stopifnot(all(unlist(lapply(
  list(params$update_index, params$share_range, params$anisotropy, params$qq_residuals, params$starr_mode),
  is.logical
))))
```


```{r params}
species <- params$species
region <- params$region
covariate_type <- gsub(" ", "-", gsub("\\/", "-", tolower(params$covariate_type)))
update_model <- params$update_model
update_index <- params$update_index

plot_index <- TRUE
# paste("survey =", region)
# paste("model type =", params$covariate_type)
family <- delta_gamma()

if (region == "Coast-wide trawl surveys") {
  region <- c("SYN QCS", "SYN HS", "SYN WCVI", "SYN WCHG")
}
```

Settings used in this report:

```{r print-params}
.p <- params
.p$starr_mode <- NULL
.p$update_index <- NULL
.p$update_model <- NULL
.p$silent <- NULL
.p$qq_residuals <- NULL
if (region == "SYN WCHG") .p$cutoff <- .p$cutoff_wchg
.p$cutoff_wchg <- NULL
print(.p)
```

<!-- Get species data  -->

```{r dat}
spp <- gsub(" ", "-", gsub("\\/", "-", tolower(species)))

data <- readRDS(here("data/all-survey-sets-2021-select.rds")) %>%
  filter(species_common_name == tolower(species)) %>%
  filter(survey_abbrev %in% region)

# change from per m2 to per km2:
data$density <- data[["density_kgpm2"]] * 1000000
data$log_depth <- log(data$depth_m)
data$area_swept1 <- data$doorspread_m * (data$speed_mpm * data$duration_min)
data$area_swept2 <- data$tow_length_m * data$doorspread_m
data$area_swept <- ifelse(!is.na(data$area_swept2), data$area_swept2, data$area_swept1)
# data$area_swept <- data$area_swept2

data <- dplyr::filter(data, !(year == 2014 & survey_abbrev == "SYN WCHG")) # not used
data <- dplyr::filter(data, !is.na(area_swept)) # should be captured by above line

# plot(data$density_kgpm2, data$catch_weight / data$area_swept)
# cor(data$density_kgpm2, data$catch_weight / data$area_swept)
# cor(data$density_kgpm2, data$catch_weight / data$area_swept1)
# cor(data$density_kgpm2, data$catch_weight / data$area_swept2)

positive_sets <- data %>%
  filter(density != 0) %>%
  filter(survey_abbrev %in% region)
data <- data %>% filter(survey_abbrev %in% unique(positive_sets$survey_abbrev))
ssid_string <- paste0(unique(data$survey_series_id), collapse = "n")
# surv_string <- paste0(unique(data$survey_abbrev), collapse = ", ")
data <- sdmTMB::add_utm_columns(data, c("longitude", "latitude"), utm_crs = 32609)
```

```{r load-coast}
coast <- gfplot:::load_coastline(range(data$longitude) + c(-0.5, 0.5),
  range(data$latitude) + c(-0.5, 0.5),
  utm_zone = 9
)
coords <- coord_equal(expand = FALSE, xlim = range(data$X) + c(-10, 10), ylim = range(data$Y) + c(-10, 10))
utm_labs <- labs(x = "Easting", y = "Northing")
```

```{r raw-data-plot, fig.cap="Plot of raw data. Sets with zero catch are shown as crosses. Area and colour of circles corresponds to set density."}
french <- FALSE
en2fr <- rosettafish::en2fr
plot_multiyear_survey_sets <- function(dat, survey_abbrev,
                                       density_lab = "", french = FALSE) {
  density_lab <- paste(en2fr("Density", translate = french), expression((kg / km^2)))
  ggplot(filter(dat, density > 0), aes(X, Y,
    size = density,
    fill = density
  )) +
    scale_size_area(max_size = 8) +
    geom_point(data = filter(dat, density == 0), pch = 4, 
      size = 0.7, col = "grey60") +
    coords +
    geom_point(alpha = 0.5, pch = 21) +
    facet_wrap(~year) +
    geom_polygon(
      data = coast, aes_string(x = "X", y = "Y", group = "PID"),
      fill = "grey87", col = "grey70", lwd = 0.2, inherit.aes = FALSE
    ) +
    scale_fill_viridis_c(trans = "sqrt") +
    labs(
      fill = density_lab,
      size = density_lab, x = en2fr("Easting", translate = french),
      y = en2fr("Northing", translate = french)
    ) +
    guides(
      size = guide_legend(order = 1),
      fill = guide_colorbar(order = 0)
    )
}

plot_multiyear_survey_sets(data, region)
```

<!-- Make mesh -->

```{r mesh, fig.width=8.5, fig.height=8.5, out.width="50%", fig.cap="SPDE (stochastic partial differential equation) mesh used during model fitting."}
# standard settings
cutoff <- params$cutoff
spatiotemporal <- "iid"

if (region %in% c("SYN WCHG")) {
  cutoff <- params$cutoff_wchg
}
spde <- make_mesh(data, xy_cols = c("X", "Y"), cutoff = cutoff)
ggplot() +
  geom_polygon(
    data = coast, aes_string(x = "X", y = "Y", group = "PID"),
    fill = "grey87", col = "grey70", lwd = 0.2, inherit.aes = FALSE) +
  scale_fill_viridis_c(trans = "sqrt") +
  inlabru::gg(spde$mesh) +
  geom_point(data = data, mapping = aes(X, Y), alpha = 0.5, pch = 21) +
  ggtitle("SPDE mesh") +
  coord_equal(expand = FALSE, xlim = range(data$X) + c(-30, 30), ylim = range(data$Y) + c(-30, 30)) +
  utm_labs
# spde$mesh$n
```

```{r load-cached}
# Check if a model and/or index already exist
dir.create("models", showWarnings = FALSE)
f <- here(paste0("models/m-", spp, "-", ssid_string, "-", covariate_type, ".rds"))
if (file.exists(f)) {
  m <- readRDS(f)
} else {
  update_model <- TRUE
}

f2 <- here(paste0("indices/i-", spp, "-", ssid_string, "-", covariate_type, ".rds"))
if (!file.exists(f2)) {
  update_index <- TRUE
}
```

<!-- Run sdmTMB model -->

```{r fit-models, eval=update_model}
update_index <- TRUE

if (covariate_type == "no-depth") {
  formula <- catch_weight ~ 0 + as.factor(year)
} else {
  if (covariate_type == "with-depth") {
    formula <- catch_weight ~ 0 + as.factor(year) + s(log_depth, k = 5)
  }
}

set_priors <- sdmTMBpriors(
  matern_s = pc_matern(range_gt = 5, sigma_lt = 3),
  matern_st = pc_matern(range_gt = 5, sigma_lt = 3)
)
ctrl <- sdmTMBcontrol(newton_loops = 1L)

fitted_type <- "delta-Gamma model with spatial and spatiotemporal random fields"
m <- try(sdmTMB(
  formula,
  data,
  mesh = spde,
  time = "year",
  family = family,
  spatial = "on",
  offset = log(data$area_swept),
  spatiotemporal = "iid",
  share_range = params$share_range,
  anisotropy = params$anisotropy,
  silent = params$silent,
  control = ctrl
))

s <- sanity(m)

if ((!s$all_ok && isTRUE(family$delta)) || class(m) == "try-error") {
  fitted_type <- "delta-Gamma model with spatial random fields"
  m1 <- try(update(m, spatiotemporal = list("off", "iid")))
  s <- sanity(m)
}

if ((!s$all_ok && isTRUE(family$delta)) || class(m) == "try-error") {
  fitted_type <- "Tweedie model with spatial and spatiotemporal random fields"
  m <- try(update(
    m,
    family = tweedie(),
    spatiotemporal = "iid"
  ))
  s <- sanity(m)
}

if ((!s$all_ok && isTRUE(family$delta)) || class(m) == "try-error") {
  fitted_type <- "Tweedie model with spatial random fields"
  m <- try(update(
    m,
    family = tweedie(),
    spatiotemporal = "off",
  ))
  s <- sanity(m)
}

m$fitted_type <- fitted_type
saveRDS(m, file = here(paste0(
  "models/m-", spp, "-", ssid_string, "-", covariate_type, ".rds"
)))
```

```{r read-model, warning = TRUE, message = TRUE, eval=!update_model}
m <- readRDS(here(paste0(
  "models/m-", spp, "-", ssid_string, "-", covariate_type, ".rds"
)))
```

The fitted model is a `r m$fitted_type`.

```{r print-model}
print(m)
```

Basic checks of model convergence:

```{r sanity, message=TRUE, warning=TRUE}
s <- sanity(m)
```

Dispersion and random effect parameter estimates:

```{r tidy}
tidy(m, effects = "ran_pars", conf.int = TRUE) %>% 
  tibble::as_tibble() %>% 
  select(-std.error)
if (length(m$call$family) > 1L) {
  tidy(m, effects = "ran_pars", conf.int = TRUE, model = 2L) %>%
    tibble::as_tibble() %>% 
    select(-std.error)
}
```

```{r plot-aniso, fig.cap="Anisotropy ranges"}
if (isTRUE(params$anisotropy)) {
  sdmTMB:::plot_anisotropy2(m)
}
```

```{r residuals, warning = FALSE, message = FALSE, eval=params$qq_residuals, fig.cap="QQ residuals"}
# if (!s$all_ok) {
#   plot_index <- FALSE
#   update_index <- FALSE
#   print("Model still not converging.")
# } else {
#   r <- residuals(m, "mle-mcmc", mcmc_warmup = 100, mcmc_iter = 101, model = 1L)
#   r2 <- r != Inf
#   if (!all(r2)) {
#     r3 <- r[r2]
#     qqnorm(r3)
#     qqline(r3)
#     update_index <- FALSE
#     plot_index <- FALSE
#     print(" Some residuals are infinite, so not calculating index.")
#   } else {
#     qqnorm(r, main = "Model 1 QQ plot")
#     qqline(r)
#   }
#   if (length(m$family$family) > 1L) {
#     r <- residuals(m, "mle-mcmc", mcmc_warmup = 100, mcmc_iter = 101, model = 2L)
#     qqnorm(r, main = "Model 2 QQ plot")
#     qqline(r)
#   }
# }
```

<!-- Load grid -->

```{r load-grid, message=FALSE, warning=FALSE}
nd <- readRDS(here("grids/synoptic_grid.rds")) %>%
  filter(survey == region)

model_ssid <- data$survey_series_id[1]

# if (region == "Coast-wide trawl surveys") {
#   nd <- readRDS(here("data-generated/nd_whole_coast_index.rds")) %>%
#     mutate(cell_area = 4e+6)
# }

nd$cell_area <- 4e+6
```

<!-- Get index -->

```{r make-grid}
make_grid <- function(x, years) {
  .x <- x
  years <- sort(unique(years))
  .nd <- do.call(
    "rbind",
    replicate(length(years), .x, simplify = FALSE)
  )
  .nd$year <- rep(years, each = nrow(.x))
  .nd
}

fitted_yrs <- sort(unique(m$data$year))

nd <- make_grid(nd, years = fitted_yrs)
nd <- na.omit(nd)
nd$year <- as.integer(nd$year)
nd$log_depth <- log(nd$depth)
```

```{r get-index, eval=update_index}
p <- predict(m, newdata = nd, return_tmb_object = TRUE)

saveRDS(p$data, here(paste0(
  "predictions/p-", spp, "-", ssid_string, "-", covariate_type, ".rds"
)))

i <- get_index(p, area = nd$cell_area, bias_correct = TRUE)

i <- i %>% mutate(
  species = species,
  survey = region,
  surveys = paste(unique(positive_sets$survey_abbrev), collapse = ", "),
  ssids = paste(unique(positive_sets$survey_series_id), collapse = ", "),
  ssid_string = ssid_string,
  family = if (length(m$family$family) > 1) m$family$clean_name else m$family$family,
  anisotropy = params$anisotropy,
  spatiotemporal = paste(c(m$call$spatiotemporal), collapse = " "),
  share_range = params$share_range,
  model = covariate_type,
  max_grad = max(m$gradients)
)
saveRDS(i, here(paste0("indices/i-", spp, "-", ssid_string, "-", covariate_type, ".rds")))
```

<!-- Map predictions -->

```{r check-delta}
is_delta <- length(m$family$family) > 1
f <- here(paste0("predictions/p-", spp, "-", ssid_string, "-", covariate_type, ".rds"))
has_predictions <- file.exists(f)
```

```{r plot-map-func}
plot_map <- function(dat, column) {
  ggplot(dat, aes_string("X", "Y", fill = column)) +
    geom_polygon(
      data = coast, aes_string(x = "X", y = "Y", group = "PID"),
      fill = "grey87", col = "grey70", lwd = 0.2, inherit.aes = FALSE) +
    geom_raster() +
    scale_colour_viridis_c() +
    scale_fill_viridis_c() +
    coord_fixed() +
    coords +
    utm_labs
}
```

```{r plot-predictions-tw, eval=plot_index && !is_delta && has_predictions, fig.cap="Predictions from the Tweedie model.",eval=FALSE}
p2 <- readRDS(f)
plot_map(p2, "est") +
  facet_wrap(~year) +
  ggtitle("Fixed + random effects in link space")
```

```{r plot-predictions-binom, eval=plot_index && is_delta && has_predictions, fig.cap="Predictions from the binomial model."}
p2 <- readRDS(f)
plot_map(p2, "plogis(est1)") +
  facet_wrap(~year) +
  labs(fill = "Probability\nof encounter", colour = "Probability\nof encounter") +
  ggtitle("Binomial model of encounter probability.") +
  # scale_colour_viridis_c(option = "C") +
  scale_fill_viridis_c(option = "C", limits = c(0, 1)) +
  guides(fill = guide_colourbar())
```

```{r plot-predictions-gamma, eval=plot_index && is_delta && has_predictions, fig.cap="Predictions from the Gamma model catch given encounter."}
plot_map(p2, "exp(est2)") +
  facet_wrap(~year) +
   scale_fill_viridis_c(
    trans = "sqrt", na.value = "yellow",
    limits = c(0, quantile(exp(p2$est2), 0.99))
  ) +
  labs(fill = "Biomass per m^2\ngiven encounter", colour = "Biomass per m^2\ngiven encounter") +
  ggtitle("Gamma model of positive catch.")
```

```{r plot-biomass, eval=plot_index && has_predictions, fig.cap="Predictions of biomass density."}
p <- predict(m, newdata = nd, type = "response")
plot_map(p, "est") +
  facet_wrap(~year) +
  scale_fill_viridis_c(
    trans = "sqrt", na.value = "yellow",
    limits = c(0, quantile(p$est, 0.99))
  ) +
  labs(fill = "Biomass per m^2", colour = "Biomass per m^2") +
  ggtitle("Overall biomass density estimates")
```

```{r plot-index, eval=plot_index, out.width="50%", fig.width = 8, fig.cap="Standardized index."}
f <- here(paste0("indices/i-", spp, "-", ssid_string, "-", covariate_type, ".rds"))
if (file.exists(f)) {
  i <- readRDS(f)
  g <- ggplot(i, aes(year, est / 1000))
  
  if (!params$starr_mode) {
    g <- g + geom_line(alpha = 0.3, lty = 1, lwd = 0.5) +
      geom_ribbon(aes(ymin = lwr / 1000, ymax = upr / 1000),
        alpha = 0.2, fill = "grey60"
      )
  }
  g <- g + geom_pointrange(aes(ymin = lwr / 1000, ymax = upr / 1000),
    alpha = 1, colour = "grey20"
  ) +
    ylab("Biomass (tonnes)") +
    ggtitle(paste(species), subtitle = paste0(region)) +
    coord_cartesian(
      ylim = c(0, max(i$upr / 1000) * 1.03),
      expand = FALSE, xlim = range(i$year) + c(-0.25, 0.25)
    ) +
    theme(axis.title.x = element_blank())
  ggsave(here(paste0("figs/", spp, "-", ssid_string, covariate_type, ".png")),
    height = 4, width = 6
  )
  g
}
```
